version: "3.9"
services:
  db:
    image: postgres:15
    container_name: convohub-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: convo
      POSTGRES_PASSWORD: convo
      POSTGRES_DB: convohub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
